name: gurobi_example_setup
channels:
  - conda-forge
  - mamba
  - gurobi # Add this line to include Gurobi's Conda channel
dependencies:
  - python
  - black
  - isort
  - pip
  - typer
  - loguru
  - tqdm
  - ipykernel
  - ipython
  - jupyter
  - jupyterlab
  - jupyter_client
  - jupyter_core
  - matplotlib
  - notebook
  - numpy
  - pandas
  - scikit-learn
  - seaborn
  - gurobi
  - pip:
      - python-dotenv
      - mkdocs
      - -e .
